### ISSUE TITLE
v1.0.0

### ISSUE THREAD

**Issue by jamesplease** [jamesplease/react-over#23]
For the first release, we're going to scale things back. It'll focus _solely_ on modals that are positioned against the window.

#### Todo

- [ ] Documentation
- [ ] API refactors ( #13 )
- [ ] Remove references to arrows in the source
- [ ] Add focus trap ( #11 )
- [ ] Some more tests ( #8 )
